name: SQL Project Deployment

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SQL Deploy
        uses: azure/sql-action@v2.3
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }} # Your connection string
          path: './database/AdventureWorksLT/AdventureWorksLT.sqlproj'
          action: 'publish'
          build-arguments: '-c Release'                 # Optional build options
          arguments: '/p:DropObjectsNotInSource=true'   # Optional properties for SqlPackage
