name: SQL Project Deployment

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: 'cwiederspan/adventureworksdab'
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: azure/docker-login@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push
        run: |
          docker build ./dab -f ./dab/Dockerfile -t $IMAGE_NAME:${{ github.sha }} -t $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest

  provision:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy Bicep file
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: ${{ vars.BASE_NAME }}
          template: ./infra/main.bicep
          parameters: 'baseName=${{ vars.BASE_NAME}} location=${{ vars.LOCATION }} databaseName=${{ vars.SQL_DB_NAME }} sqlUsername=${{ vars.SQL_USERNAME }} sqlPassword=${{ secrets.SQL_PASSWORD }}'
          failOnStdErr: false

  deploy:
    runs-on: ubuntu-latest
    needs: provision
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SQL Deploy
        uses: azure/sql-action@v2.3
        with:
          connection-string: 'Server=tcp:${{ vars.BASE_NAME }}-sql.database.windows.net,1433;Initial Catalog=${{ vars.SQL_DB_NAME }};Persist Security Info=False;User ID=${{ vars.SQL_USERNAME }};Password=${{ secrets.SQL_PASSWORD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'   # Your connection string
          path: './database/AdventureWorksLT/AdventureWorksLT.sqlproj'
          action: 'publish'
          build-arguments: '-c Release'                 # Optional build options
          arguments: '/p:DropObjectsNotInSource=true'   # Optional properties for SqlPackage
